import { FullSlug } from "../../util/path"
import { QuartzEmitterPlugin } from "../types"
import { write } from "./helpers"

// Makes the site an installable Progressive Web App.
// Emits /manifest.webmanifest and /sw.js at the site root (a service worker only controls
// pages at or below its own path, so it cannot live in /static/).
// The <link rel="manifest"> and icon tags live in components/Head.tsx.

interface Options {
  shortName: string
  description: string
}

const defaultOptions: Options = {
  shortName: "LIBEROS",
  description: "A living knowledge base on strategy, military affairs and public policy.",
}

// Runs in the browser. VERSION is replaced at build time so every deploy gets fresh caches.
const serviceWorker = (version: string) => `// generated by quartz/plugins/emitters/pwa.ts
const VERSION = ${JSON.stringify(version)}
const PAGES = "pages-" + VERSION
const ASSETS = "assets-" + VERSION
const PRECACHE = [
  "./",
  "./404.html",
  "./index.css",
  "./prescript.js",
  "./postscript.js",
  "./static/contentIndex.json",
  "./static/icon.svg",
  "./static/icon-192.png",
]
// Third-party hosts whose files are safe to keep offline (fonts, KaTeX/Mermaid CDN)
const CDN_HOSTS = ["fonts.googleapis.com", "fonts.gstatic.com", "cdnjs.cloudflare.com", "cdn.jsdelivr.net"]

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(PAGES).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()))
})

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => !k.endsWith(VERSION)).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  )
})

// Pages and data: network first, so readers always get the latest notes; cache is the offline fallback.
async function networkFirst(request) {
  const cache = await caches.open(PAGES)
  try {
    const response = await fetch(request)
    if (response.ok) cache.put(request, response.clone())
    return response
  } catch {
    return (
      (await cache.match(request, { ignoreSearch: true })) ||
      (await cache.match("./404.html")) ||
      Response.error()
    )
  }
}

// Static assets: serve from cache immediately, refresh in the background.
async function staleWhileRevalidate(request) {
  const cache = await caches.open(ASSETS)
  const cached = await cache.match(request)
  const refresh = fetch(request)
    .then((response) => {
      if (response.ok || response.type === "opaque") cache.put(request, response.clone())
      return response
    })
    .catch(() => cached)
  return cached || refresh
}

self.addEventListener("fetch", (event) => {
  const request = event.request
  if (request.method !== "GET") return
  const url = new URL(request.url)

  if (url.origin !== self.location.origin) {
    if (CDN_HOSTS.includes(url.hostname)) event.respondWith(staleWhileRevalidate(request))
    return
  }

  const isPageOrData = request.mode === "navigate" || /(\\/|\\/[^./]+|\\.(html|json|xml))$/.test(url.pathname)
  event.respondWith(isPageOrData ? networkFirst(request) : staleWhileRevalidate(request))
})
`

export const Pwa: QuartzEmitterPlugin<Partial<Options>> = (userOpts) => {
  const opts = { ...defaultOptions, ...userOpts }
  return {
    name: "Pwa",
    // Register the worker. It is left out of live-reload dev builds, where its caching would get in
    // the way, unless LIBEROS_PWA=1 (`make serve-pwa`). The manifest link is already resolved to the
    // site root, so sw.js is found from any page depth and under any sub-path.
    externalResources(ctx) {
      if (ctx.argv.serve && process.env.LIBEROS_PWA !== "1") return {}
      return {
        js: [
          {
            loadTime: "afterDOMReady",
            contentType: "inline",
            spaPreserve: true,
            script: `if ("serviceWorker" in navigator) {
  const manifest = document.querySelector('link[rel="manifest"]')
  if (manifest) navigator.serviceWorker.register(new URL("sw.js", manifest.href))
}`,
          },
        ],
      }
    },
    async *emit(ctx) {
      const cfg = ctx.cfg.configuration
      const colors = cfg.theme.colors.darkMode
      const manifest = {
        name: cfg.pageTitle,
        short_name: opts.shortName,
        description: opts.description,
        lang: cfg.locale,
        // relative to the manifest, so this also works when hosted under a sub-path
        id: "./",
        start_url: "./",
        scope: "./",
        display: "standalone",
        display_override: ["window-controls-overlay", "standalone"],
        background_color: colors.light,
        theme_color: colors.light,
        categories: ["education", "books", "news"],
        icons: [
          { src: "static/icon.svg", sizes: "any", type: "image/svg+xml", purpose: "any" },
          { src: "static/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
          { src: "static/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
          {
            src: "static/icon-maskable-512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable",
          },
        ],
        shortcuts: [
          { name: "Concepts", url: "./02-Concepts/" },
          { name: "Assessments", url: "./05-Assessments/" },
          { name: "Learning", url: "./09-Learning/" },
        ],
      }

      yield write({
        ctx,
        slug: "manifest" as FullSlug,
        ext: ".webmanifest",
        content: JSON.stringify(manifest, null, 2),
      })

      yield write({
        ctx,
        slug: "sw" as FullSlug,
        ext: ".js",
        content: serviceWorker(new Date().toISOString()),
      })
    },
    async *partialEmit() {},
  }
}
